"""fix_task_assignment_and_reactions

Revision ID: 3c74ac85d04e
Revises: 36594d3bec15
Create Date: 2026-01-01 15:36:32.956527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c74ac85d04e'
down_revision: Union[str, Sequence[str], None] = '36594d3bec15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###